#!/bin/bash

pdb_check=$(git grep -E -n 'import i?pdb|set_trace\(\)')

if [ ${#pdb_check} -gt 0 ]
then
        echo "COMMIT REJECTED: commit contains code with break points"
        echo $pdb_check
        exit 1
else
        echo "Code contains no break points"
fi

exit 0
